[package]
name = "shardedrw"
version = "0.1.0"
edition = "2024"

[dependencies]
lope = { path = "../lope", features = ["std"] }
crossbeam-utils = { version = "0.8.21", default-features = false }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
rand = "0.10.2"

[[bench]]
name = "main_benchmarks"
harness = false
