# This workflow checks whether the library is able to run without the std library (e.g., embedded).
# This entire file should be removed if this crate does not support no-std. See check.yml for
# information about how the concurrency cancellation and workflow triggering works
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: no-std
jobs:
  nostd_pass:
    runs-on: ubuntu-latest
    name: ${{ matrix.target }}
    strategy:
      matrix:
        target: [aarch64-unknown-none, thumbv7m-none-eabi]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # branch=master
        with:
          toolchain: stable
      - name: rustup target add ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}
      - name: cargo check
        run: cargo check --target ${{ matrix.target }} --no-default-features
